[phases.setup]
nixpkgsArchive = '9fc02ad42e892d6710316378f3d63ea79af87c8c'
nixPkgs = [
    "...",

    # Fix for coollabsio/coolify/issues/4202 (LICENSE file collision)
    '(lib.hiPrio php83Packages.composer)',
]

[phases.build]
cmds = [
    "cp /app/nixpacks/start.sh /assets/start.sh",
    "chmod +x /assets/start.sh",
    "chown -R www-data /app/storage",
    "chown -R www-data /app/bootstrap/cache",
    "...",
]

[start]
cmd = '/assets/start.sh'
