[phases.setup]
nixpkgsArchive = '9fc02ad42e892d6710316378f3d63ea79af87c8c'
nixPkgs = [
    "...",

    # Fix for coollabsio/coolify/issues/4202 (LICENSE file collision)
    '(lib.hiPrio php83Packages.composer)',
]

# Nixpacks only offers pnpm 9, so run the pnpm version in package.json through corepack
[phases.install]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --ignore-platform-reqs",
    "COREPACK_ENABLE_DOWNLOAD_PROMPT=0 corepack pnpm install --frozen-lockfile",
]

[phases.build]
cmds = [
    "cp /app/nixpacks/start.sh /assets/start.sh",
    "chmod +x /assets/start.sh",
    "chown -R www-data /app/storage",
    "chown -R www-data /app/bootstrap/cache",
    "COREPACK_ENABLE_DOWNLOAD_PROMPT=0 corepack pnpm run build",
]

[start]
cmd = '/assets/start.sh'
