name: CD

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: If all is well, deploy
        run: curl ${{ secrets.DEPLOYMENT_WEBHOOK }}
